# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: JRTP701-MiniProj01-CURDOperations
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jrtp_db
    username: root
    password: 757052
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 4041

plan:
  module:
    messages:
      save-success: Travel Plan is saved with id value
      save-failure: Travel plan is not saved with Value
      find-by-id-failure: Travel Plan is not found
      update-success: Travel Plan is updated
      update-failure: Travel Plan is not found for updation
      delete-success: Travel Plan is deleted
      delete-failure: Travel Plan is not found for deletion
      status-change-success: Travel Plan is deleted
      status-change-failure: Travel Plan is not found for deletion